### Build container
FROM rust:alpine as build

WORKDIR /src

RUN git clone <service_repo_url> .
RUN cargo build --release
RUN strip /src/target/release/service

### App container
FROM blockjoy/base
COPY ./main.rhai /var/lib/babel/plugin/

COPY --from=build /src/target/release/service /usr/bin/

