### Build container
FROM rust:alpine as build

WORKDIR /src

RUN touch dummy_service
#RUN git clone <service_repo_url> .
#RUN cargo build --release
#RUN strip /src/target/release/service

### App container
FROM ubuntu:24.10
COPY ./main.rhai /var/lib/babel/plugin/

COPY --from=build /src/dummy_service /usr/bin/
